//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQLUsingEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualSalary
    {
        public string cEmployeeCode { get; set; }
        public Nullable<decimal> mAnnualSalary { get; set; }
        public short siYear { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
