//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQLUsingEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractRecruiter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractRecruiter()
        {
            this.ExternalCandidates = new HashSet<ExternalCandidate>();
        }
    
        public string cContractRecruiterCode { get; set; }
        public string cName { get; set; }
        public string vAddress { get; set; }
        public string cCity { get; set; }
        public string cState { get; set; }
        public string cZip { get; set; }
        public string cFax { get; set; }
        public string cPhone { get; set; }
        public Nullable<short> siPercentageCharge { get; set; }
        public Nullable<decimal> mTotalPaid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalCandidate> ExternalCandidates { get; set; }
    }
}
