//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQLUsingEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AnnualSalaries = new HashSet<AnnualSalary>();
            this.EmployeeReferrals = new HashSet<EmployeeReferral>();
            this.MonthlySalaries = new HashSet<MonthlySalary>();
            this.Skills = new HashSet<Skill>();
        }
    
        public string cEmployeeCode { get; set; }
        public string vFirstName { get; set; }
        public string vLastName { get; set; }
        public string cCandidateCode { get; set; }
        public string vAddress { get; set; }
        public string cCity { get; set; }
        public string cState { get; set; }
        public string cZip { get; set; }
        public string cCountryCode { get; set; }
        public string cPhone { get; set; }
        public string vQualification { get; set; }
        public Nullable<System.DateTime> dBirthDate { get; set; }
        public string cSex { get; set; }
        public string cCurrentPosition { get; set; }
        public string cDesignation { get; set; }
        public string cEmailId { get; set; }
        public string cDepartmentCode { get; set; }
        public string cRegion { get; set; }
        public byte[] imPhoto { get; set; }
        public Nullable<System.DateTime> dJoiningDate { get; set; }
        public Nullable<System.DateTime> dResignationDate { get; set; }
        public string cSocialSecurityNo { get; set; }
        public string cSupervisorCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnualSalary> AnnualSalaries { get; set; }
        public virtual Country Country { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeReferral> EmployeeReferrals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlySalary> MonthlySalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
