//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQLUsingEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalCandidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalCandidate()
        {
            this.EmployeeReferrals = new HashSet<EmployeeReferral>();
            this.Skills = new HashSet<Skill>();
        }
    
        public string cCandidateCode { get; set; }
        public string vFirstName { get; set; }
        public string vLastName { get; set; }
        public string vAddress { get; set; }
        public string cCity { get; set; }
        public string cState { get; set; }
        public string cZip { get; set; }
        public string cCountryCode { get; set; }
        public string cPhone { get; set; }
        public string cPositionCode { get; set; }
        public Nullable<System.DateTime> dDateOfApplication { get; set; }
        public string cEmployeeReferralNo { get; set; }
        public string cNewsAdNo { get; set; }
        public string cAgencyCode { get; set; }
        public string cContractRecruiterCode { get; set; }
        public string cJobFairCode { get; set; }
        public string cCampusRecruitmentCode { get; set; }
        public string cExEmployeeCode { get; set; }
        public string vQualification { get; set; }
        public Nullable<short> siPrevWorkExperience { get; set; }
        public Nullable<System.DateTime> dBirthDate { get; set; }
        public string cSex { get; set; }
        public string cCollegeCode { get; set; }
        public Nullable<decimal> mPrevAnnualSalary { get; set; }
        public byte[] imPhotograph { get; set; }
        public string vEmailId { get; set; }
        public string cStatus { get; set; }
        public Nullable<System.DateTime> dTestDate { get; set; }
        public Nullable<short> siTestScore { get; set; }
        public Nullable<System.DateTime> dInterviewDate { get; set; }
        public string cInterviewer { get; set; }
        public string vInterviewComments { get; set; }
        public string cRating { get; set; }
    
        public virtual CampusRecruitment CampusRecruitment { get; set; }
        public virtual ContractRecruiter ContractRecruiter { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeReferral> EmployeeReferrals { get; set; }
        public virtual RecruitmentAgency RecruitmentAgency { get; set; }
        public virtual JobFair JobFair { get; set; }
        public virtual NewsAd NewsAd { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
