//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQLUsingEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalCandidate
    {
        public string cCandidateCode { get; set; }
        public string cEmployeeCode { get; set; }
        public string cInternalJobPostingCode { get; set; }
        public string cPositionCodeAppliedFor { get; set; }
        public Nullable<System.DateTime> dDateOfApplication { get; set; }
        public Nullable<System.DateTime> dTestDate { get; set; }
        public Nullable<short> siTestScore { get; set; }
        public Nullable<System.DateTime> dInterviewDate { get; set; }
        public string cInterviewer { get; set; }
        public string vInterviewComments { get; set; }
        public string cRating { get; set; }
        public string cStatus { get; set; }
    
        public virtual InternalJobPosting InternalJobPosting { get; set; }
        public virtual Position Position { get; set; }
    }
}
