//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQLUsingEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobFair
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobFair()
        {
            this.ExternalCandidates = new HashSet<ExternalCandidate>();
        }
    
        public string cJobFairCode { get; set; }
        public string vLocation { get; set; }
        public string vJobFairCompany { get; set; }
        public Nullable<decimal> mFee { get; set; }
        public Nullable<System.DateTime> dFairDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalCandidate> ExternalCandidates { get; set; }
    }
}
