//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQLUsingEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsAd
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewsAd()
        {
            this.ExternalCandidates = new HashSet<ExternalCandidate>();
        }
    
        public string cNewsAdNo { get; set; }
        public string cNewspaperCode { get; set; }
        public Nullable<System.DateTime> dAdStartDate { get; set; }
        public Nullable<System.DateTime> dDeadline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalCandidate> ExternalCandidates { get; set; }
        public virtual Newspaper Newspaper { get; set; }
    }
}
