//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQLUsingEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string cSourceCode { get; set; }
        public Nullable<decimal> mAmount { get; set; }
        public string cChequeNo { get; set; }
        public System.DateTime dDate { get; set; }
    }
}
