//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqToSQLUsingEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        public string cRequisitionCode { get; set; }
        public string cPositionCode { get; set; }
        public Nullable<System.DateTime> dDateofRequisition { get; set; }
        public Nullable<System.DateTime> dDeadline { get; set; }
        public string cDepartmentCode { get; set; }
        public string vRegion { get; set; }
        public Nullable<short> siNoOfVacancy { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
